Always inherit platformFeePercent from the host
opencollective/opencollective-api pull request #4514
Opened 2020-09-04 11:30 UTC by kewitz

This means resetting the platformFeePercent when moving from a host with fees on top to a host without.

2020-09-04 12:56 UTC, znarf commented on server/models/Collective.js
> +    const platformFeePercent = this.tags?.includes('covid-19') ? 0 : hostCollective.platformFeePercent;
What about `EVENT` and `PROJECT`? How do we make sure they inherit their parent?

2020-09-10 07:59 UTC, znarf requested changes
I don't get where/how Events and Projects are inheriting the platformFeePercent of their parent.

2020-09-10 11:22 UTC, kewitz commented
@znarf I was counting on the whole creation/cascading flow for that.
I'll make it explicit.

2020-09-10 11:28 UTC, znarf commented
@kewitz case to support: a Covid-19 collective decide to join another Host and the Host have platformFeePercent=5, the Events of this Collective should have platformFeePercent=0 (from the parent) and not platformFeePercent=5 (from the host).

2020-09-10 11:30 UTC, kewitz commented
@znarf yep, in the case the event or project is not tagged with `covid-19`. Just pushed the fix.

2020-09-10 18:22 UTC, merged