Allow transferwise.availableCurrencies blacklist to be bypassed
opencollective/opencollective-api pull request #4550
Opened 2020-09-11 14:55 UTC by kewitz

This is useful to generate a generic bank account form without the intent to be used in TransferWise.

2020-09-11 18:30 UTC, znarf commented
Following Up on https://github.com/opencollective/opencollective-api/pull/4276 let's try to avoid the term "blacklist" from now on.

2020-09-11 19:38 UTC, kewitz commented
@znarf thanks for the heads up! I'll refactor these PRs and use the new terms.d

2020-09-12 07:49 UTC, znarf requested changes
"blocklist" is a good replacement to "blacklist" as a noun.

However, I think "block" is better than "blocklist" as a verb, so "blockListedCurrencies" -> "blockedCurrencies".

2020-09-14 06:58 UTC, Betree reviewed
`blockedCurrencies` sounds better to me too, the rest looks good :+1:

2020-09-14 13:19 UTC, merged