enhancement(collective.member.created): Add summary suffix to email subject
opencollective/opencollective-api pull request #5165
Opened 2021-01-24 17:21 UTC by Yetizone

Fixes https://github.com/opencollective/opencollective/issues/3823

Besides adding the suffix described in the issue this PR also adds some mock data for the email template in `compile-email.js`
I used the mock data for testing, but since there was no other previous data I thought I might as well leave it in the commit.

Used MailDev for testing: 
![MailDev_Screenshot](https://user-images.githubusercontent.com/43905913/105638016-2b926400-5e79-11eb-83de-376126b7df01.png)

2021-01-24 18:17 UTC, Yetizone commented
Ah, the changes broke some of the tests. I'll mark this as Draft while I look into the failing tests.

2021-02-01 21:03 UTC, Yetizone commented
Just finished fixing the `test-graphql` test which was broken by the changes in this PR. 

Looking at the output of the other failing tests, they don't seem to be related to the patch though so I think I'll mark this as ready. Do let me know if I'm mistaken and there's anything else that needs to be done.

2021-02-04 10:18 UTC, Betree reviewed
Looking good so far! Some improvement suggestions below

2021-02-04 10:18 UTC, Betree commented on test/server/graphql/v1/mutation.test.js
> +          expect(emailSendMessageSpy.secondCall.args[1]).to.equal("Google joined Scouts d'Arlon as backer $20/m");
Would be great to have that in parenthesis as proposed in the issue

```suggestion
          expect(emailSendMessageSpy.secondCall.args[1]).to.equal("Google joined Scouts d'Arlon as backer ($20/m)");
```

2021-02-04 10:18 UTC, Betree commented on server/lib/handlebars.js
> +handlebars.registerHelper('formatOrderSummary', order => {
Something a bit more explicit there would be welcome. I can propose:

```suggestion
handlebars.registerHelper('formatOrderAmountWithInterval', order => {
```

2021-02-04 10:18 UTC, Betree commented on server/lib/handlebars.js
> +  let ret = formatCurrencyObject(currencyObj);
Simpler alternative using `formatCurrency` from `server/lib/utils.js` + explicit variable name:

```suggestion
  const formattedAmount = formatCurrency(order.totalAmount, order.currency);
```

2021-02-04 16:57 UTC, Yetizone commented
Done! I've pushed an updated version of the patch with the recent suggestions.

2021-02-08 10:58 UTC, Betree requested changes
I just tried locally and it doesn't seem to be working. Here's how I tested:
- Go to /apex/donate (logged out)
- Make a contribution
- Check email on http://localhost:1080

![image](https://user-images.githubusercontent.com/1556356/107210710-cf951700-6a04-11eb-9951-a17ee7e26428.png)

2021-02-08 10:58 UTC, Betree commented on server/lib/handlebars.js
> +  if (order.currency === null || order.totalAmount === null) {
In case the fields are undefined

```suggestion
  if (!order.currency || !order.totalAmount) {
```

2021-02-10 00:20 UTC, Yetizone commented
I've just pushed an updated version of the patch.

When donating from `/apex/donate`, `order.subscription.interval` exists but it's set to null. Instead there's `order.interval` which is set to the proper value. 

The new logic now checks if the fields exist and are not null. While writing this I was wondering if both `order.subscription.interval` and `order.interval` should exist, considering that they are very similar, but that would be a separate issue.

2021-02-15 17:04 UTC, Betree reviewed
Looks good! Tests are not passing, but it seems unrelated to the changes here. I'll try to rebase to see if that helps.

2021-02-15 17:04 UTC, Betree commented on server/lib/handlebars.js
> +  }
This can be simplified as:

```suggestion
  const interval = subscription?.interval || order.interval;
```

2021-02-15 17:04 UTC, Betree commented on server/lib/handlebars.js
> +    return formattedAmountWithInterval;
We can simplify here too

```suggestion
    if (interval === 'month') {
      return `(${formattedAmount}/m)`;
    } else if (interval === 'year') {
      return `(${formattedAmount}/y)`;
    }
```

2021-02-16 16:49 UTC, Yetizone commented
Done! Just pushed an updated version of the patch with the recent suggestions.

2021-02-26 10:44 UTC, Betree commented
I'm moving this to https://github.com/opencollective/opencollective-api/pull/5437, tests are usually not running great on forks

2021-02-26 10:44 UTC, closed without merging

2021-02-26 12:18 UTC, Yetizone commented
> tests are usually not running great on forks

Oh alright, that's good to know.