fix: use DEBIT transaction when refunding expenses
opencollective/opencollective-api pull request #6601
Opened 2021-09-16 22:21 UTC by kewitz

Related to https://opencollective.freshdesk.com/a/tickets/35682

2021-09-17 07:32 UTC, znarf commented
I don't have enough to understand the problem and review the PR.

What is the case we're looking at? Why was getHostCollective() failing here? Is there something special? Is this new?

Please details in the PR or code comments.

2021-09-17 11:48 UTC, kewitz commented
@znarf there's a link to the support ticket in the PR with more context on the real problem.

To summarize, at the beginning of `createRefundTransaction` we do:
```js
/* If the transaction passed isn't the one from the collective
* perspective, the opposite transaction is retrieved. */
if (transaction.type === DEBIT) {
  transaction = await transaction.getRelatedTransaction({ type: CREDIT });
}
```
And if the we're also refunding payment processor fees, in `refundPaymentProcessorFeeToCollective()` we'll create the refund transactions with:
```js
 await models.Transaction.createDoubleEntry({
    type: CREDIT,
    kind: TransactionKind.PAYMENT_PROCESSOR_COVER,
    CollectiveId: transaction.CollectiveId,
    FromCollectiveId: transaction.HostCollectiveId,
    HostCollectiveId: transaction.HostCollectiveId,
    ...
});
```

The issue is that, if we're dealing with an Expense, the credit transaction is attributed to the user and not the collective.
What we really want is to have the Host of the collective covering for the payment processor fees charged when paying for the expense.
That's why we should use the debit transaction when dealing with an expense.

2021-09-17 12:28 UTC, znarf commented
> Why was getHostCollective() failing here? Is there something special? Is this new?

2021-09-17 12:36 UTC, kewitz commented
> Why was getHostCollective() failing here? Is there something special? Is this new?
It fails because, on an expense transaction, we'll create a double transaction with
```js
const fromCollective = await models.Collective.findByPk(transaction.FromCollectiveId);
const fromCollectiveHost = await fromCollective.getHostCollective();
```
and we call that with the "FromCollectiveId" being the host of the receiving user (who usually does not have a host).
More importantly, it makes zero sense to refund the payment processor fee of an expense to the user.

2021-09-17 12:41 UTC, znarf commented
> const fromCollective = await models.Collective.findByPk(transaction.FromCollectiveId);

No reason for me to have `fromCollective = null`. I don't get it.

> More importantly, it makes zero sense to refund the payment processor fee of an expense to the user.

Happy so see this challenged, I don't see the justification for this.

2021-09-17 12:46 UTC, znarf commented
I now understand that `transaction.FromCollectiveId = otherTransaction.HostCollectiveId`.

I think we should fail earlier because we're not supposed to even try to create a Transaction with `FromCollectiveId=null`.

2021-09-17 12:47 UTC, kewitz commented
> No reason for me to have `fromCollective = null`. I don't get it.

The CREDIT transaction of an expense will have no `HostCollectiveId` because it credits the `ColletiveId` of the user.
Therefore, when you call `createDoubleEntry` on `refundPaymentProcessorFeeToCollective` you're calling
```js
await models.Transaction.createDoubleEntry({
    type: CREDIT,
    kind: TransactionKind.PAYMENT_PROCESSOR_COVER,
    CollectiveId: transaction.CollectiveId,
    FromCollectiveId: null,
    HostCollectiveId: null,
    ...
});
```

> Happy so see this challenged, I don't see the justification for this.
When you pay for an expense, you're debiting credit from the collective and paying the user. If you're refunding and the host is covering for the payment fees, the cover should go from the host to the collective.

2021-09-17 12:56 UTC, znarf commented
>>> More importantly, it makes zero sense to refund the payment processor fee of an expense to the user.

>> Happy so see this challenged, I don't see the justification for this.

> When you pay for an expense, you're debiting credit from the collective and paying the user. If you're refunding and the host is covering for the payment fees, the cover should go from the host to the collective.

Do we really want to do a `PAYMENT_PROCESSOR_COVER` scheme for Expenses? 

Let's say, yes. I would like to see some test coverage for that case in: https://github.com/opencollective/opencollective-api/blob/main/test/stories/ledger.test.ts

2021-09-20 16:07 UTC, znarf requested changes
As written before, please add test coverage for the case in:
https://github.com/opencollective/opencollective-api/blob/main/test/stories/ledger.test.ts

2021-09-20 18:37 UTC, znarf commented on server/lib/payments.js
> +      const transactionToRefundPaymentProcessorFee = transaction.ExpenseId
Maybe `transaction.kind === EXPENSE` would have been more semantical.

2021-09-20 18:37 UTC, znarf approved these changes

2021-09-20 20:32 UTC, merged