Remove the older `supportedPaymentMethodService` field and relavant logic
opencollective/opencollective-api pull request #7411
Opened 2022-04-13 19:20 UTC by SudharakaP

Related to the discussion at, https://github.com/opencollective/opencollective-api/pull/7359#discussion_r849163069. We are not using `supportedPaymentMethodService` and we should be default use the `searchCollectivesInDB` when we are doing search. Thus I propose refactoring this part to remove the unnecessary logic.

2022-04-14 13:12 UTC, Betree reviewed
Not the way to go with the public API. First, deprecate then remove after some time.

We don't know whether people depend on this or not.

2022-04-22 09:30 UTC, znarf requested changes
Deprecate first.

2022-04-22 13:53 UTC, SudharakaP commented
> Deprecate first.

Done at, https://github.com/opencollective/opencollective-api/pull/7440

2023-06-08 12:57 UTC, Betree approved these changes
Rebased & solved conflicts

2023-06-08 13:30 UTC, merged