Move `geoLocationLatLong` to JSONB
opencollective/opencollective-api pull request #7457
Opened 2022-04-26 10:53 UTC by Betree

As per https://github.com/opencollective/opencollective/issues/3171, this removes the dependency on Postgis.

Sequelize was converting all `GEOMETRY(POINT)` to objects like `{ type: 'POINT', coordinates: [0, 0] }` (basically what we get by calling `st_asgeojson`). Storing the JSONB directly seems to have the exact same effect regarding the model usage. Since no query depends on it, it seems that there's nothing more to do.

2022-04-27 06:40 UTC, znarf requested changes
Looks good! Unfortunately, the migration doesn't seems to work in CI.

2022-04-27 08:23 UTC, Betree commented
> Looks good! Unfortunately, the migration doesn't seems to work in CI.

Yep it came in with my last change which `DROP EXTENSION postgis`. I may keep that out of the PR for now

2022-04-27 11:45 UTC, znarf approved these changes
Excellent. Next step is to remove the dependency fully in documentation and setup instructions.

Maybe we will have to update our development data dump so it doesn't need postgis?

2022-04-29 13:04 UTC, Betree commented
> Excellent. Next step is to remove the dependency fully in documentation and setup instructions.
> 
> Maybe we will have to update our development data dump so it doesn't need postgis?

Exactly. I posted the next steps in https://github.com/opencollective/opencollective/issues/3171#issuecomment-1109726932

2022-04-29 13:04 UTC, merged