Add support for receipt templates (for non-tax deductible payments)
opencollective/opencollective-api pull request #7709
Opened 2022-07-04 12:43 UTC by SudharakaP

Related to https://github.com/opencollective/opencollective/issues/5368

2022-07-06 13:55 UTC, SudharakaP commented
Just to note that the GraphQL Inspector issue is not related to this; I've opened an issue and fixed this at, https://github.com/opencollective/opencollective/issues/5724

2022-07-06 16:14 UTC, kewitz requested changes
Make sure invoice templates are always referenced by key on Tier and Transactions for the sake of consistency.
The template should only live in the host collective data.

2022-07-07 23:23 UTC, SudharakaP commented on migrations/20220630124848-move-invoice-details-to-invoiceTemplates.js
> +      UPDATE "Collectives" SET settings = jsonb_set("settings", '{invoice, templates}', '{}') WHERE ("settings" -> 'invoiceTitle') IS NOT NULL;
I've changed this line to save the steps as you suggested. 👍🏽

2022-07-10 20:17 UTC, kewitz approved these changes

2022-07-13 13:22 UTC, merged