Add Expense Security Checks
opencollective/opencollective-api pull request #8084
Opened 2022-10-18 14:43 UTC by kewitz

Resolves https://github.com/opencollective/opencollective/issues/5183

2022-10-19 14:32 UTC, hdiniz commented on server/graphql/common/expenses.ts
> +export const canSeeExpenseSecurityChceks: ExpensePermissionEvaluator = async (req, expense) => {
typo:
```suggestion
export const canSeeExpenseSecurityChecks: ExpensePermissionEvaluator = async (req, expense) => {
```

2022-10-19 14:32 UTC, hdiniz commented on server/graphql/v2/object/Expense.js
> +          if (await ExpenseLib.canSeeExpenseSecurityChceks(req, expense)) {
```suggestion
          if (await ExpenseLib.canSeeExpenseSecurityChecks(req, expense)) {
```

2022-10-24 16:26 UTC, vaughanj10 requested changes
This looks really good! Nice job! :smile: 

I have a couple of requests around adding tests for `checkExpense`, and adding some clarifying comments in the code.

2022-10-24 20:02 UTC, kewitz commented on server/lib/security/expense.ts
> +  const checkStats = async (where, { scope, details }: { scope: Scope; details?: string }) => {
I agree. I much rather compose functional expressions.

2022-10-24 20:04 UTC, kewitz commented on server/lib/security/expense.ts
> +export const checkExpense = async (expense: typeof models.Expense): Promise<SecurityCheck[]> => {
Unfortunately, these tests are not set in stone, and user requests are very subjective.
I'll add a generic test to make sure this works as expected, but I'll ignore any parameters and specifics for now.

2022-10-25 13:24 UTC, merged